// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3p99hFyHmM8FajZnApm544Hjx_l7xub4',
    appId: '1:563597744247:web:6b90a898aabf41e2888e72',
    messagingSenderId: '563597744247',
    projectId: 'shareway-f6764',
    authDomain: 'shareway-f6764.firebaseapp.com',
    storageBucket: 'shareway-f6764.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtz9qkK_aYazJw0llydsF7sP10d8uaGsg',
    appId: '1:563597744247:android:8c3591b9c95c614b888e72',
    messagingSenderId: '563597744247',
    projectId: 'shareway-f6764',
    storageBucket: 'shareway-f6764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyVfOtr8Y3HnHN44GN0j-YUYQ9yg-60W0',
    appId: '1:563597744247:ios:871af361051c96bb888e72',
    messagingSenderId: '563597744247',
    projectId: 'shareway-f6764',
    storageBucket: 'shareway-f6764.firebasestorage.app',
    iosBundleId: 'com.shareway.shareway',
  );
}
